openapi: 3.0.3
info:
  title: Zai REST API Weather Service
  description: |-
    This service reports on the temperature of locations (cities) in Australia. The service returns a JSON payload with a unified response
     containing the temperature (in degrees celsius) and the wind speed (in km/hr).
  contact:
    email: colin.schofield@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /weather:
    get:
      summary: Returns the temperature and wind speed of the specified city.
      description: If no city is given, it defaults to Melbourne.
      parameters:
        - name: city
          in: query
          description: The name of the city (which must be in Australia)
          required: false
          explode: true
          schema:
            type: string
            default: Melbourne
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather200'
        '404':
          description: Invalid city value
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather404'
components:
  schemas:
    Weather200:
      required:
        - wind_speed
        - temperature_degrees
      type: object
      properties:
          status:
            type: integer
            example: 200
          message:
            type: string
            example: Request successful
            description: Message
          data:
            type: object
            properties:
              temperature_degrees:
                type: integer
                example: 29
              wind_speed:
                type: integer
                example: 20
    Weather404:
      required:
        - wind_speed
        - temperature_degrees
      type: object
      properties:
          status:
            type: integer
            example: 404
          message:
            type: string
            example: Location could not be found
            description: Message